# Site settings
title: Singapore gophers
tag_text: Singapore Gophers
description: Singapore Gophers is a community of programmer, hobbyist who use Golang in Singapore

# Build settings
markdown: kramdown

exclude: ["README.md"]
